segmentio/analytics-react-native

- README.md
- package.json
- packages/core/package.json
- packages/core/src/__tests__/bridge.spec.ts
- packages/core/src/bridge.ts
- packages/integrations/src/gen-integrations.ts
- packages/integrations/template/index.js
- yarn.lock
Improve the error message when a native module is not found at runtime. This will make issues like #4 easier to debug.
Ref: LIB-654
> fix(bridge): improve missing native module error

- packages/core/android/build.gradle
- packages/integrations/template/android/build.gradle
If the host react native application is using a different version of the android sdk build tools, build warnings will be displayed about incompatibilities.  This addresses that by using the values defined in the root project.
This is the approach used by the current [react-native-create-library template](https://github.com/frostney/react-native-create-library/blob/master/templates/android.js#L28).
> Pull android tool versions from root project

- packages/core/src/analytics.ts
The comments for the `recordScreenViews` and `trackAppLifecycleEvents` were swapped. I just re-ordered the comments so they can match the correct property.
> Swap config comments to match their respective config option.

- packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
- packages/core/docs/classes/analytics.client.md
- packages/core/ios/RNAnalytics/RNAnalytics.m
- packages/core/src/__tests__/configuration.spec.ts
- packages/core/src/analytics.ts
- packages/core/src/bridge.ts
- packages/core/src/configuration.ts
Ref: LIB-891
Fixes #16 
Closes #15
> fix(core): fix duplicate client error in dev mode

- .circleci/config.yml
This adds filters to jobs that publish depends on so that the publish job can run on tags.
Reference: https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag.
> ci(publish): fix publish job

- packages/test-app/package.json
- packages/test-app/test_android.sh
The end to end tests for detox aren't actually being run during the `test-android` step, just the detox app is built.
The build fails with the following error, because yarn cannot find the detox binary:
This adds the detox command to `package.json` in the test app.
> Fix android detox build

- packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
Fixes #36
Application lifecycle events (Application Installed, Opened, Updated) in Android are not being tracked.
In the analytics-android package, lifecycle events being tracked in the callback of [`onActivityCreated`](https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L292). However, neither `onActivityCreated` or `onActivityStarted` are ever called when using this library via the native wrapper. The other lifecycle methods, e.g. `onActivityResumed`, `onActivityPaused`, `onActivityStopped` etc are called as expected, which makes this a React Native specific bug.
The most likely reason for this is that `MainActivity` is created to run the React Native app before the native Analytics client is initialised, so that …
> Move application lifecycle tracking in Android to the native wrapper

- CHANGELOG.md
properly call out that 1.0.1 did not include the fixes from `1.0.1-beta.0`
> docs(changelog): update 1.0.1 changelog

- packages/core/package.json
Adds a `prepublish` step to `core`. `integrations` doesn't need it as packages are pre-built.
Tested with:
```bash
$ cd packages/core
$ npm publish --dry-run
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
> @segment/analytics-react-native@1.0.1 prepublish .
> yarn build
yarn run v1.16.0
$ run-s build:{clean,ts,pkg}
npm WARN lifecycle The node binary used for scripts is /var/folders/f6/nps199ns421g6qcxh2_93tk00000gn/T/yarn--1560352057410-0.6452185138163682/node but npm is using /usr/local/Cellar/node/12.3.1/bin/node itself. Use the `--scripts-prepend-node-path` …
```
> chore(core): add prepublish step

- packages/core/docs/classes/analytics.client.md
- packages/core/src/__tests__/configuration.spec.ts
- packages/core/src/analytics.ts
- packages/core/src/configuration.ts
Update the React Native iOS configuration to enable tracking by default, same as the [native iOS library](https://github.com/segmentio/analytics-ios/blob/d1db92dab26b75ae7a8cba925604d41c464b0051/Analytics/Classes/SEGAnalyticsConfiguration.m#L55).
> feat(ios): set trackAdvertising=true by default

- packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
Previously the track application call was set on the builder after it was passed to the build with integrations call. We want to call it before ensuring the boolean is set when the builder creates the Analytics singleton.
> Support Lifecycle Tracking

- packages/integrations/template/android/build.gradle
- Fixes #90 
- Changed integration template to use Gradle 1.3.21
> fix(core): fix kotlin gradle version for integrations

- packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
Currently, if exception occurs when calling `setSingletonInstance` , we are rejecting it.
It prevents us using the singleton created at native side from RN.
If the exception is due to calling `setSingletonInstance` twice, we let the `setup` call resolve rather than reject so that RN can properly set itself up and use the singletonInstance created by native android.
This fixes https://github.com/segmentio/analytics-react-native/issues/95
> allow native and RN to share singleton instance

- packages/core/android/build.gradle
After upgrading the gradle version of our project, `react-native` test task failed. 
This pull request is using Kotlin version from the root project if available to prevent android test task errors
> Use KotlinVersion of root project if available 

- packages/core/android/build.gradle
- packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
- packages/core/docs/README.md
- packages/core/docs/classes/analytics.client.md
- packages/core/docs/interfaces/analytics.configuration.md
- packages/core/src/bridge.ts
- packages/core/src/middleware.ts
- packages/integrations/template/android/build.gradle
- Fixed issue where context changes weren't passing thru to android.
- Fixed nullability mismatch between what the android lib specified and what was defined in RN.
- Fixed gradle project identifiers.
> fix(android): fixed context not passing thru

- packages/core/android/build.gradle
- packages/core/docs/classes/analytics.client.md
- packages/core/docs/interfaces/analytics.configuration.md
- packages/integrations/src/gen-integrations.ts
- packages/integrations/template/android/build.gradle
- Fixes issue w/ defaultKotlinVersion not being found in android's build.gradle.
- Fixes dependency reference change.
- Fixes segment reference in integration generator.
> Post-Beta Release Fixes

- packages/core/android/build.gradle
Android builds might fail at the moment with following error message:
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '…/node_modules/@segment/analytics-react-native/android/build.gradle' line: 45
> 
> * What went wrong:
> A problem occurred evaluating project ':@segment_analytics-react-native'.
> > Could not get unknown property 'defaultKotlinVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
The scope of the variable `defaultKotlinVersion` was not correctly set in #157 and should be fixed with this PR. (This problem is also solved by #158 but this approach does not need to set the same variable twice.)
> fix(android): defaultKotlinVersion

- packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
- packages/core/ios/RNAnalytics/RNAnalytics.m
LAPP-31
An error with a label "Duplicate Analytics client" is displayed following the next steeps.
1.- Install and build the app on a iOS simulator.
2.- Setup the analytics object inside the project (I'm following setup instructions on segment doc).
3.- After run the simulator, modify the setup variables and save, this will reload the app and crash.
4.- An error must be displayed.
> fix(bridge): fix duplicated analytics client improving errors

- packages/integrations/template/android/build.gradle
When Android running builds I'm getting the following issue:
```* Where:
Build file '/Users/.../node_modules/@segment/analytics-react-native-adjust/android/build.gradle' line: 41
* What went wrong:
A problem occurred evaluating project ':@segment_analytics-react-native-adjust'.
> Project with path ':@segment/analytics-react-native' could not be found in project ':@segment_analytics-react-native-adjust'.
```
Above change seems to fix.
> Fix build issue with integrations

- packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalytics.kt
- packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
- packages/core/docs/README.md
- packages/core/docs/classes/analytics.client.md
- packages/core/docs/interfaces/analytics.configuration.md
- packages/integrations/applyPatches.sh
- packages/integrations/patches/@segment/analytics-react-native-adjust/android/src/main/java/com/segment/analytics/reactnative/integration/adjust/IntegrationModule.kt
- packages/integrations/src/gen-integrations.ts
- packages/integrations/template/android/src/main/java/com/segment/analytics/reactnative/integration/Module.kt
It has been noticed that the Adjust integration does not function as expected on RN Android, the reason being when the app is freshly installed the Android `onResume` lifecycle function is not intercepted and thus functionality implemented there is not executed.
This PR exposes the `onReadyIntegration` to all integrations within RN and implements an Adjust specific behavior allowing us to force call the `onResume` function
> [Android] Force integration:Adjust.onResume

- .circleci/config.yml
- packages/core/RNAnalytics.podspec
- packages/core/android/build.gradle
- packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
- packages/core/android/src/main/java/com/segment/analytics/reactnative/core/Utils.kt
- packages/core/docs/classes/analytics.client.md
- packages/core/docs/interfaces/analytics.configuration.md
- packages/core/ios/RNAnalytics/RNAnalytics.h
- packages/core/ios/RNAnalytics/RNAnalytics.m
- packages/core/src/__tests__/configuration.spec.ts
- packages/core/src/analytics.ts
- packages/core/src/bridge.ts
- packages/core/src/configuration.ts
- packages/integrations/integrations.yml
- packages/integrations/template/ios/main.m
- packages/test-app/test_ios.sh
This change exposes the new setup configuration property to include default project settings in case Segment.com cannot be reached (preventing fetching project settings from Segment).
> [Feature] add support for supplying defaultProjectSettings

- packages/core/src/analytics.ts
- packages/core/src/middleware.ts
User supplied is not being utilised, this PR fixes that by setting it alongside the default context
Single test to ensure context is added before sending across the bridge
> Fix user-supplied context

- README.md
Given the requirement in the readme of RN 0.62, it's better to replace the link command with the pod install step, as required by the [autolinking cli documentation](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md).
(in fact, the link command doesn't do the pod install so the installation would be incomplete without it)
> Improve installation section of README

- .circleci/config.yml
- package.json
- packages/core/RNAnalytics.podspec
- packages/integrations/applyPatches.sh
- packages/integrations/patches/@segment/analytics-react-native-facebook-app-events-ios/ios/main.m
- packages/integrations/template/Pod.podspec
- packages/test-app/package.json
- packages/test-app/patches/Podfile
- packages/test-app/patches/TestApp.xcodeproj/project.pbxproj
- packages/test-app/patches/TestApp.xcodeproj/xcshareddata/xcschemes/TestApp.xcscheme
- packages/test-app/seed/ios/TestApp-Bridging-Header.h
- packages/test-app/seed/ios/TestApp-tvOS-Bridging-Header.h
- packages/test-app/seed/ios/TestApp.xcodeproj/project.pbxproj
- packages/test-app/seed/ios/TestApp.xcodeproj/xcshareddata/xcschemes/TestApp.xcscheme
- packages/test-app/seed/ios/TestApp/Dummy.swift
- packages/test-app/seed/ios/TestAppTests/TestAppTests.m
- packages/test-app/seed/package.json
- yarn.lock
- Fixes issues w/ header slug creation.
- Fixes issues w/ non-segment owned integrations not building and needing updates.
- Fixes issue w/ running test app w/ Facebook-app-events integration.
- Fixes pod spec mismatch between analytics-ios and analytics-react-native.
- Fixes issue w/ package.json not referencing correction versions for supported RN builds.
- Fixes pod spec to use new format of imports for RN 0.62+
> fix(ios): fixes for building for newer rn

- packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
- packages/core/docs/README.md
- packages/core/docs/classes/analytics.client.md
- packages/core/docs/interfaces/analytics.configuration.md
- packages/core/ios/RNAnalytics/RNAnalytics.m
- packages/core/src/analytics.ts
- packages/core/src/bridge.ts
- packages/core/src/configuration.ts
extended the configuration API to allow directing analytics traffic through a hosted proxy (or other)
I noticed that the native [iOS](https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/#proxy-http-calls) and [Android](https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/#proxy-http-calls) SDK's had support for proxying http requests. The current RN module did not have this capability so I simply ported it over.
> feat(core): http proxying via setup configuration

- README.md
This is a followup of [this PR](https://github.com/segmentio/analytics-react-native/pull/192) updating the README.
The Device mode Destination packages can be autolinked as well.
> Replace manual linking instructions in README with pod install

- packages/core/RNAnalytics.podspec
- packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalytics.kt
- packages/core/docs/README.md
- packages/core/docs/classes/analytics.client.md
- packages/core/docs/interfaces/analytics.configuration.md
- packages/core/ios/RNAnalytics/RNAnalytics.m
- packages/core/src/__tests__/configuration.spec.ts
- packages/core/src/analytics.ts
- packages/core/src/bridge.ts
- packages/core/src/configuration.ts
- packages/test-app/patches/TestApp.xcodeproj/Podfile
- IDFA for iOS is now required to be set externally.
- Advertising tracking now defaults to false.
- setIDFA(string) will now need to be called from within react-native.
- setIDFA() defined as a no-op on Android.
- see https://www.npmjs.com/package/react-native-idfa for querying IDFA on iOS.
> feat(ios): make idfa for ios external to analytics

- packages/core/ios/RNAnalytics/RNAnalytics.m
`proxyOptions[@"scheme"]` is already a string. Calling `stringValue` on `NSString` causes the following runtime crash on iOS <=12. 
```
NSInvalidArgumentException
-[NSTaggedPointerString stringValue]: unrecognized selector sent to instance 0xa000073707474685
```
Debugger says it's invalid:
> Fix crash when using proxy on iOS 12

- packages/core/android/build.gradle
- packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
- packages/core/docs/classes/analytics.client.md
- packages/core/src/analytics.ts
Closes https://github.com/segmentio/analytics-react-native/issues/255
As outlined in https://github.com/segmentio/analytics-android/issues/725, we are adding the builder `experimentalUseNewLifecycleMethods(bool)` to react-native to disable the use of the new lifecycle methods. This flag is enabled by default and can be disabled on react-native like so
```js
analytics.setup(SEGMENT_WRITE_KEY, {
...
android: {
...,
experimentalUseNewLifecycleMethods: false
},
});
```
> [Android] opt-out of new lifecycle methods

- packages/core/RNAnalytics.podspec
Latest Xcode 12 fails to build while without a module to depend on React-Core directly hence this change is necessary for all native modules on iOS. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
Use this branch to install with an app running on Xcode 12.
> fix: Xcode 12 compatibility

- packages/core/ios/RNAnalytics/RNAnalytics.m
- Fixes issue with the header import compatibility for analytics-ios 3.x vs 4.x
> chore(dep): fix include for analytics-ios 3.x vs 4.x

- .circleci/config.yml
- packages/core/package.json
- packages/integrations/src/gen-integrations.ts
> fix(package): missing repo info

- packages/test-app/seed/android/app/build.gradle
- packages/test-app/seed/android/app/src/main/AndroidManifest.xml
- packages/test-app/seed/android/build.gradle
- packages/test-app/seed/android/gradle.properties
Android CI was failing silently due to manifest conflicts. We have now migrated to the new androidx libraries to resolve the issue. Closes #269
> Fix android test-app CI failure

- README.md
Remove GA from the list of react device-mode sdks. Google forced folks to move mobile implementations to Firebase.
> Don't use GA, use firebase

- packages/integrations/template/ios/main.m
Sometimes, mainly on iOS, I'm losing the integration with some libs, like AppsFlyer or Firebase.
We set up as described on [device-mode doc](https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/#packaging-destinations-using-device-mode) but sometimes the received payload on Segment was missing some of the defined integrations.
example of a correct payload passing `using: [AppsFlyer, Firebase]`: 
```
"integrations": {
"AppsFlyer": false,
"Firebase": false
}
```
As described on the issue #61 those event informations were being lost and I could find the root cause of the problem.
Debugging I found some intermittent behaviour in this part of the [code](https://github.com/segmentio/analytics-react-native/blob/40683c7c70d4a750d947fe7117962b0c09cb1936/packages/core/i …
> fix: iOS losing integrations on Setup

- packages/core/android/build.gradle
- packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
- Bump analytics-android to 4.9.3
- Fix nullable write-key issue
- Disable experimental lifecycle methods
> Bump Analytics-android dependency

- packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
This change re-adds the invocation of the function to track `Application Installed` and `Application Opened` events on cold-boot
> Fix Tracking Application Installed and Application Opened on cold-boot

- .circleci/config.yml
Fixing the install command in circleCI to install applesimutils
> fix: ci brew applesimutils

- example/src/App.tsx
- packages/core/android/src/main/java/com/segmentanalyticsreactnative/AnalyticsReactNativeModule.kt
- packages/core/src/analytics.ts
- packages/core/src/context.ts
- packages/core/src/types.ts
> fix: add fix for deviceId on android builds

- package.json
- yarn.lock
resolves dependabot alerts for `nanoId` and `shelljs`
updates `nanoId` and `release-it`
> Bump Dependencies

- README.md
- example/android/.project
- example/android/.settings/org.eclipse.buildship.core.prefs
- example/android/app/src/main/AndroidManifest.xml
- example/android/app/src/main/java/com/example/segmentanalyticsreactnative/MainActivity.java
- example/android/app/src/main/java/com/example/segmentanalyticsreactnative/MainApplication.java
- example/ios/AnalyticsReactNativeExample.xcodeproj/project.pbxproj
- example/ios/AnalyticsReactNativeExample.xcodeproj/xcshareddata/xcschemes/AnalyticsReactNativeExample.xcscheme
- example/ios/AnalyticsReactNativeExample/AnalyticsReactNativeExample.entitlements
- example/ios/AnalyticsReactNativeExample/AppDelegate.h
- example/ios/AnalyticsReactNativeExample/AppDelegate.m
- example/ios/Podfile.lock
- example/src/App.tsx
- example/yarn.lock
- packages/core/android/.project
- packages/core/android/.settings/org.eclipse.buildship.core.prefs
- packages/core/android/build.gradle
- packages/core/android/src/main/java/com/segmentanalyticsreactnative/AnalyticsReactNativeModule.kt
- packages/core/ios/AnalyticsReactNative.swift
- packages/core/segment-analytics-react-native.podspec
- packages/core/src/__tests__/__helpers__/mockSegmentStore.ts
- packages/core/src/__tests__/internal/trackDeepLinks.test.ts
- packages/core/src/analytics.ts
- packages/core/src/storage/sovranStorage.ts
- packages/core/src/storage/types.ts
- yarn.lock
- feat: add deeplink functionality
- fix: upgrade Sovran, add logs to test deeplink data
- refactor: refactor android native code
- refactor: refactor trackDeepLinks method
- fix: changed how to access the SovranModule from the activity
- feat: android deeplink tracking without any configuration, added trackDeeplink method to iOS
- feat: added ios trackDeepLink method and added instructions to readme
> feat: enhanced deeplink tracking. Include referralApplication in the deeplink track functions.

- example/ios/Podfile.lock
- packages/core/src/analytics.ts
- packages/core/src/util.ts
> feat: add reset to plugins

- README.md
- add the Taplytics Destination plugin as an example to the README
> docs: add Taplytics under Example Plugins

- README.md
Users can remain in the "managed workflow" (where they don't have `ios/` or `android/` directories in their project and only write JS) by using dev clients and EAS Build. The limitation that exists for this library is that it won't work in Expo Go.
> Clarify Expo support

- packages/core/src/analytics.ts
- packages/plugins/plugin-appsflyer/src/AppsflyerPlugin.tsx
Fixes AppsFlyer plugin not reporting install events due to the condition being always false:
Types in `appsflyer-react-native` package are wrongly reporting `is_first_launch: "true" | "false";`
But at runtime, these are actual boolean values.
https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/index.d.ts#L12
Also added extra safety JSON.parse based on the examples in https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/DeepLink.md#-1-deferred-deep-linking-get-conversion-data
Also, fixed types for `analytics.add(plugin)`
> fix: appsflyer attribution

- README.md
- packages/core/src/client.tsx
- packages/core/src/storage/__tests__/sovranStorage.test.ts
- packages/core/src/storage/sovranStorage.ts
- packages/core/src/storage/types.ts
- packages/core/src/types.ts
The gist of this PR is that it allows for a `storePersistor` client option to be specified in the `createClient` function call. Currently `@segment/sovran-react-native`, the store that backs `@segment/analytics-react-native`, uses `AsyncStorage` as the default persistor. However with this changeset, the new client option allows for Segment clients to leverage a storage mechanism other than `AsyncStorage`.
Gopuff's app uses MMKV for key/value storage. And the Consumer Platform Team required that MMKV be the storage mechanism for `@segment/analytics-react-native`'s stores. Hopefully this enhancement will be beneficial to other Segment client as well.
Updated README.md's section on **Client Options**. Hopefully that was sufficient. Please let me know if additional documentation is required. …
> feat: createClient "storePersistor" option

- README.md
Currently, the documentation for screen tracking in React Navigation requires manually implementing a utility to determine the focused screen and can also result in `Unknown` screen. This updates the documentation to follow the official React Navigation docs to use the built-in methods instead.
The example app also needs to be updated, but currently, I don't have time to do this.
Note: I didn't use `useNavigationRef` to stay compatible with React Navigation 5.
Docs: https://reactnavigation.org/docs/screen-tracking
> docs: update screen tracking for React Navigation

- packages/plugins/plugin-appsflyer/src/AppsflyerPlugin.tsx
This PR prevents the `onInstallConversionData` handler from throwing an error when the SDK is not able to get the conversion data. In this case, `res?.data?.is_first_launch` would be undefined and `JSON.parse` would fail.
Sample payload in `onInstallConversionData` that would cause this error:
```
{
status: 'failure',
type: 'onInstallConversionFailure',
data: 'Launch status code: 404'
}
```
> fix: appsflyer attribution error due to install conversion data failure

- packages/plugins/plugin-idfa/ios/AnalyticsReactNativePluginIdfa.swift
The `@available(iOS 14, *)` attribute didn't prevent this function from being called by react-native / objc runtime. By what seems to be pure luck, on iOS 13 this method implementation is basically a no-op. This PR adds intentional support for iOS 13 and below by moving the iOS 14 check inside the function and handling the < iOS 14 case as well.
- No more undefined behavior
- iOS 13 users IDFAs will be captured
> feat: plugin-idfa: Add support for iOS 13 and below

- README.md
- packages/core/src/__tests__/api.test.ts
- packages/core/src/api.ts
- packages/core/src/types.ts
The gist of this PR is that it allows for a `proxy` client option to be specified in the `createClient` function call. Previously in Analytics React Native 1.0, a `proxy` client option was available in the `setup` function call.
Gopuff's Customer Data Platform team wants to be able to empower other internal engineerings teams with the ability to inspect events and assert them for integrations tests in realtime. To do this we were hoping to be able to specify a `proxy` that the events would be posted to first before we post them to Segment. `analytics-node` and `analytics-next` already have the ability to specify proxies, so we were hoping we could make it possible for `analytics-react-native`.
Updated README.md's section on **Client Options**. Hopefully that was sufficient. Please let me …
> feat: Create Client Proxy Option

- packages/plugins/plugin-facebook-app-events/src/methods/parameterMapping.ts
- packages/plugins/plugin-facebook-app-events/src/methods/track.ts
This PR:
- map the missing Checkout Started [spec’d events](https://segment.com/docs/connections/spec/) to the matching Facebook Event following the [docs](https://segment.com/docs/connections/destinations/catalog/facebook-app-events/#facebook-events).
- correctly trigger a facebook purchase event just in case the event is a `fb_mobile_purchase`. Previously the event was triggered also for events having the props `_valueToSum`, e.g. `Product Added`
> fix: map correct facebook events

- MIGRATION_GUIDE.md
- example/src/plugins/InjectTraits.ts
- packages/core/src/__tests__/methods/identify.test.ts
- packages/core/src/events.ts
- packages/core/src/types.ts
- Reverted the traits behavior to not persist after an `identify` event
- Added example plugin `InjectTraits` and documentation for how to preserve this behavior
- Added migration guide for Plugins from V1 to V2
> fix: revert traits behavior

- packages/core/src/__tests__/timeline.test.ts
- packages/core/src/plugin.ts
- packages/core/src/timeline.ts
- packages/plugins/plugin-braze/src/BrazePlugin.tsx
-  Timeline won't shortcircuit destinations if one fails or returns undefined (each DestinationPlugin should be independent)
- Fixed Braze plugin key ('Appboy')
> fix: timeline safe processing events for destinations

- packages/plugins/plugin-firebase/src/methods/___tests__/track.test.ts
- packages/plugins/plugin-firebase/src/methods/parameterMapping.ts
- packages/plugins/plugin-firebase/src/methods/track.ts
This PR:
Correctly map the following event names (the name previously used are now [deprecated](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event#public-static-final-string-ecommerce_purchase)):
- `Order Complete` maps to `purchase` instead of `ecommerce_purchase`
- `Promotion Viewed` maps to `view_promotion` instead of `present_offer`
-  `Order Refunded` maps to `refund` instead of `purchase_refund`
We also added a map for the events props inspired by the facebook event plugin, as some events were not fired if the attributes provided didn't have the correct names.
> fix: map to correct firebase event name/attributes

- example/.detoxrc.json
- example/ios/Podfile.lock
- example/package.json
- example/src/Home.tsx
- example/yarn.lock
- packages/core/package.json
- packages/core/src/__tests__/__helpers__/mockEventStore.ts
- packages/core/src/__tests__/__helpers__/mockSegmentStore.ts
- packages/core/src/__tests__/internal/handleAppStateChange.test.ts
- packages/core/src/__tests__/internal/trackDeepLinks.test.ts
- packages/core/src/__tests__/methods/alias.test.ts
- packages/core/src/__tests__/methods/identify.test.ts
- packages/core/src/__tests__/timeline.test.ts
- packages/core/src/analytics.ts
- packages/core/src/client.tsx
- packages/core/src/info.ts
- packages/core/src/plugin.ts
- packages/core/src/plugins/Context.ts
- packages/core/src/plugins/SegmentDestination.ts
- packages/core/src/plugins/__tests__/QueueFlushingPlugin.test.ts
- packages/core/src/plugins/__tests__/SegmentDestination.test.ts
- packages/core/src/storage/helpers.ts
- packages/core/src/storage/index.ts
- packages/core/src/storage/sovranStorage.ts
- packages/core/src/storage/types.ts
- packages/core/src/timeline.ts
- packages/core/src/types.ts
- packages/plugins/plugin-amplitudeSession/src/AmplitudeSessionPlugin.tsx
- yarn.lock
- fix: upgrade sovran to v0.3.0, add concurrency safe getters
- fix: support async processing in timeline
- fix: make all client methods awaitable, fix userInfo race condition
- chore: cleanup
> fix: race condition when using state changing events

- packages/plugins/plugin-facebook-app-events/README.md
Add more clarity for how customers initialize the Plugin and what methods they need to use.
> Clarify FaceBook Plugin Docs

- MIGRATION_GUIDE.md
`Application Installed` will re-fire after an upgrade from 1.x to 2.x, and this seems to be expected.
This information, along with some strategies for filtering out the extra events, is present in [your documentation at segment.com](https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/migration/), but it's missing here. Its absence made it extremely difficult and scary to figure out why our `Application Installed` events were firing so frequently.
I added what was in segment.com's migration documentation. Alternatively, this file could mostly go away – you could link to the migration documentation on segment.com from here instead 🤷
> Add information about `Application Installed` in 2.x migration

- README.md
There is zero documentation about this plugin, even searching google is missing any reference to this plugin. I only found it through an issue ticket and then searching source code for plugins. This is such a critical piece that prevents partners like Branch from working correctly without this ID. Too many hours spent on trying to find out why segment events don't show in branch.io. All basically due to all documentation missing related to getting this advertising ID.
This is still missing from any page at segment.com so someone will need to go tip off future explorers of clear documentation at Segment.
> Add Android Advertising ID plugin to plugin table in README

- packages/plugins/plugin-advertising-id/README.md
The command will now work for those copying it.
> Fix plugin yarn add command for plugin: react-native-plugin-advertising-id

- packages/plugins/plugin-advertising-id/android/build.gradle
The current minSdkVersion set at 31 is breaking builds for anyone supporting older devices.
https://developers.google.com/android/guides/setup
To test your app when using Google Play services, you must use one of the following:
A compatible Android device that runs Android 4.4 (API level 19) or higher and has the Google Play Store app installed.
The Android emulator with an AVD that runs the Google APIs platform based on Android 4.4 (API level 19) or higher.
> Set minSdkVersion to 19 per documentation for plugin-advertising-id

- README.md
- packages/core/src/__tests__/client.test.ts
- packages/core/src/analytics.ts
- packages/core/src/client.tsx
- packages/core/src/logger.ts
- packages/core/src/plugins/SegmentDestination.ts
- packages/core/src/timeline.ts
- packages/core/src/types.ts
- packages/plugins/plugin-idfa/src/IdfaPlugin.tsx
In response to issue #605 , this PR allows users to configure a custom logger via `createClient(config: Config)` as in:
```
const client = createClient({
writeKey: 'SEGMENT_KEY',
logger: customLogger
});
```
The custom logger just has to implement a simple interface `DeactivableLoggerType`.
This allows full flexibility to escalate logs, process them etc. And would effectively solve #605.
> feat: adds option to provide a custom logger object to consume library logs

- packages/plugins/plugin-firebase/src/methods/___tests__/identify.test.ts
- packages/plugins/plugin-firebase/src/methods/identify.ts
This fixes a bug where calling `identify` on the client without specifying a `userId` could result in the Firebase Plugin throwing out type errors.
> fix: avoids calling Firebase::setUserId with undefined value

- packages/plugins/plugin-braze/src/methods/__tests__/track.test.ts
- packages/plugins/plugin-braze/src/methods/track.ts
- adds safety check for attribution values in `Install Attributed` events in Braze Plugin
> fix: add null/undefined check to attribution data

- packages/core/src/plugins/DestinationMetadataEnrichment.ts
- packages/core/src/plugins/__tests__/SegmentDestination.test.ts
Our previous implementation was lacking a little, causing issues with sending data to destinations on cloud-mode.
These changes should now incorporate the list of active destinations and mark them as `unbundled` if no device-mode equivalent is present.
> Fix `_metadata` population

- README.md
- packages/core/src/__tests__/analytics.test.ts
- packages/core/src/__tests__/internal/fetchSettings.test.ts
- packages/core/src/analytics.ts
- packages/core/src/api.ts
- packages/core/src/errors.ts
- packages/core/src/index.ts
- packages/core/src/plugins/QueueFlushingPlugin.ts
- packages/core/src/plugins/SegmentDestination.ts
- packages/core/src/plugins/__tests__/SegmentDestination.test.ts
- packages/core/src/timeline.ts
- packages/core/src/types.ts
- packages/plugins/plugin-facebook-app-events/src/FacebookAppEventsPlugin.ts
- packages/plugins/plugin-idfa/src/IdfaPlugin.tsx
- packages/plugins/plugin-mixpanel/src/methods/alias.ts
- feat: added errorHandler option to client
- chore: add readme for error handlers
> feat: added errorHandler option to client

- packages/plugins/plugin-firebase/package.json
- bumps firebase to `0.3.5` to fix missing `lib` directory in npm package.
> chore: bump firebase to new version

- .gitignore
- packages/core/package.json
- packages/core/src/__tests__/util.test.ts
- packages/core/src/analytics.ts
- packages/core/src/info.ts
- packages/core/src/util.ts
- yarn.lock
Remove allSettled package method and use a local one with the same functionality.
allSettled method was throwing `Unhandled promise rejection [RangeError: Maximum call stack size exceeded.]`
> fix: refactor allSettled to remove dependencies

- packages/core/src/__tests__/methods/alias.test.ts
- packages/core/src/__tests__/methods/identify.test.ts
- packages/core/src/analytics.ts
- packages/core/src/plugins/InjectUserInfo.ts
- packages/core/src/plugins/__tests__/InjectUserInfo.test.ts
This fixes an issue where `identify` followed by a `track` call without awaiting would still end up with `userId` not being set correctly.
The order is important inside `InjectUserInfo`, previously it was locking when accessing the current user data before getting to set, which caused `track` to finish before `identify`. 
It isn't required to do a `get` before `set` as the setter will get access to its most current state when run.
Added tests to prevent regressions.
> fix: prevent locking before setting new user data

- example/ios/Podfile.lock
- packages/core/src/info.ts
- packages/plugins/plugin-appsflyer/package.json
- packages/plugins/plugin-appsflyer/src/AppsflyerPlugin.tsx
- yarn.lock
- adds support for AppsFlyer's new `onDeepLink()` method to support unified deeplinking
- bumps AppsFlyer SDK to `6.9.4`
> feat: add unified DL support to appsflyer

- example/ios/Podfile.lock
- packages/plugins/plugin-adjust/package.json
> feat: bump adjust sdk to 4.33.0 to support new features

- README.md
- example/ios/Podfile.lock
- example/package.json
- example/yarn.lock
- packages/core/package.json
- packages/core/src/__mocks__/uuid.ts
- packages/core/src/__tests__/client.test.ts
- packages/core/src/__tests__/internal/checkInstalledVersion.test.ts
- packages/core/src/__tests__/internal/handleAppStateChange.test.ts
- packages/core/src/__tests__/internal/trackDeepLinks.test.ts
- packages/core/src/__tests__/methods/alias.test.ts
- packages/core/src/__tests__/methods/flush.test.ts
- packages/core/src/__tests__/methods/group.test.ts
- packages/core/src/__tests__/methods/screen.test.ts
- packages/core/src/__tests__/methods/track.test.ts
- packages/core/src/__tests__/timeline.test.ts
- packages/core/src/info.ts
- packages/core/src/plugins/__tests__/SegmentDestination.test.ts
- packages/core/src/storage/__tests__/sovranStorage.test.ts
- packages/core/src/uuid.ts
- packages/plugins/plugin-firebase/src/methods/___tests__/track.test.ts
- packages/plugins/plugin-mixpanel/src/methods/__tests__/alias.test.ts
- yarn.lock
- Previous UUID library had instances of repeated IDs
**Important**
Requires installing new native dependency [react-native-get-random-values](https://github.com/LinusU/react-native-get-random-values) on application
> fix: switching UUID library, new depedencies

- packages/plugins/plugin-appsflyer/README.md
adds documentation clarifying additional iOS setup for deep link tracking.
> chore: Update README.md

- example/ios/Podfile.lock
- packages/core/src/info.ts
- packages/plugins/plugin-braze/src/methods/__tests__/track.test.ts
- packages/plugins/plugin-braze/src/methods/track.ts
`productId` is `product_id` in the [Segment e-commerce Spec](https://segment.com/docs/connections/spec/ecommerce/v2/#order-completed).
> fix: update product_id to match e commerce spec

- README.md
- packages/core/src/__mocks__/react-native.ts
- packages/core/src/__tests__/__helpers__/setupSegmentClient.ts
- packages/core/src/__tests__/analytics.test.ts
- packages/core/src/__tests__/internal/fetchSettings.test.ts
- packages/core/src/__tests__/methods/flush.test.ts
- packages/core/src/__tests__/methods/group.test.ts
- packages/core/src/__tests__/methods/screen.test.ts
- packages/core/src/__tests__/methods/track.test.ts
- packages/core/src/__tests__/timeline.test.ts
- packages/core/src/analytics.ts
- packages/core/src/constants.ts
- packages/core/src/flushPolicies/__tests__/background-flush-policy.test.ts
- packages/core/src/flushPolicies/background-flush-policy.ts
- packages/core/src/flushPolicies/flush-policy-executer.ts
- packages/core/src/flushPolicies/index.ts
- packages/core/src/plugins/__tests__/SegmentDestination.test.ts
- packages/plugins/plugin-clevertap/src/__tests__/ClevertapPlugin.test.ts
- packages/plugins/plugin-device-token/src/methods/___tests__/DeviceTokenPlugin.test.ts
- packages/plugins/plugin-mixpanel/src/methods/__tests__/MixpanelPlugin.test.ts
- packages/plugins/plugin-mixpanel/src/methods/__tests__/alias.test.ts
- Fixes the behaviour of `flushPolicies` to be mutually exclusive with `flushAt`/`flushInterval`. This will pevent getting the default policies when specifying only policies.
- Fixes the reference copy of the `flushPolicies` to prevent mutating the user supplied array if not destructured in the method call
- Adds tests for the `flushPolicies` from the client public methods (previously only tested in unit tests)
- Adds `BackgroundFlushPolicy` to trigger a flush when the app goes into the Background. Useful for uploading events before switching or launching a different app.
> fix: fix flush policies reference copy, add BackgroundPolicy

- packages/plugins/plugin-firebase/src/methods/track.ts
- In previous plugin of firebase segment used to remove the characters if it exceeds 40 characters.
This PR fixed this issue to maintain the backward compatibility. 
This fixes
https://ekeekaran-ventures.sentry.io/share/issue/8b521c3429fd49f39c5459b84046030a/
> fix: event name should contain 40 alphanumeric characters or underscores

- packages/core/android/build.gradle
- packages/plugins/plugin-advertising-id/android/build.gradle
Starting with RN 0.72 the JVM target will be enforced across all packages. Unfortunately in my case instead of enforcing JVM 11, I am going to have to enforce JVM 17 because that's the java version I have locally installed. 
The RN team introduced a fix which updates the `sourceCompatibility` and `targetCompatibility` in all projects to make that compatible. `kotlinOptions.jvmTarget` is by default set by the JVM version that is installed on the machine - in my case 17. At the moment, the RN fix is not updating the `kotlinOptions.jvmTarget` - I hope that will still make it as part of the 0.72.0 stable relaese. Generally the JVM target of java and kotlin needs to match. If the RN team does not decide to update their fix, then I would need to patch this library manually to fix build errors …
> fix: resolve potential build issues with RN 0.72

- example/ios/Podfile.lock
- packages/core/package.json
- packages/core/src/info.ts
- packages/core/tsconfig.json
- packages/plugins/plugin-adjust/package.json
- packages/plugins/plugin-appsflyer/package.json
- packages/plugins/plugin-branch/package.json
- packages/plugins/plugin-clevertap/package.json
- packages/plugins/plugin-destination-filters/package.json
- packages/plugins/plugin-facebook-app-events/package.json
- packages/plugins/plugin-mixpanel/package.json
- Adds `tsub` as a dependency on core (missing, only required for types)
- Fixes TS builds for correctly importing sovran types from core
- Move dependencies to peerDependencies in plugins
> fix: package dependency fixes

- .github/workflows/ci.yml
- .gitignore
- packages/core/src/__tests__/methods/process.test.ts
- packages/core/src/analytics.ts
- packages/core/src/info.ts
- Splits the logic of stamping `userInfo` and `context` out from `applyRawEventData`. This is required as the raw event data should only be basic data: `timestamp` and `messageId` that can be calculated from the start, the `userInfo` and `context` should wait for the initialization to finish
- This caused a bug where events triggered at the very start of the app, just before initialization would not contain either `userInfo` or `context`
- Added tests
- Removed `info.ts` from the build as it is  auto generated on build
> fix: split userInfo/context stamping from raw event data

- packages/plugins/plugin-firebase/package.json
I needed this change in my project otherwise it creates a dependency issue (since I'm using rn-firebase 18.4.0). I've been using this for about two weeks now without any issues, ie all segment events are being sent as expected
> Update peer dependency to version 18 of Firebase

- packages/core/src/flushPolicies/background-flush-policy.ts
- Added a check for `currentState` to allow for the `unknown` value occasionally generated by RN per this [GH issue](https://github.com/facebook/react-native/issues/37793) in iOS. This will prevent the backgroundFlushPolicy from failing on initial launch.
> fix: add unknown option to current state

- example/e2e/mockServer.js
- packages/core/src/__tests__/api.test.ts
- packages/core/src/api.ts
Changes the Upload HTTP Content-Type header to json utf-8 to align with Swift/Kotlin
> fix: change content type to json

- packages/core/src/plugin.ts
- packages/core/src/plugins/ConsentPlugin.ts
- packages/core/src/plugins/__tests__/consent/consentNotEnabledAtSegment.test.ts
- packages/core/src/plugins/__tests__/consent/consentNotEnabledAtSegment.ts
- packages/core/src/plugins/__tests__/consent/destinationMultipleCategories.test.ts
- packages/core/src/plugins/__tests__/consent/mockSettings/ConsentNotEnabledAtSegment.json
- packages/core/src/plugins/__tests__/consent/mockSettings/DestinationsMultipleCategories.json
- packages/core/src/plugins/__tests__/consent/mockSettings/NoUnmappedDestinations.json
- packages/core/src/plugins/__tests__/consent/mockSettings/UnmappedDestinations.json
- packages/core/src/plugins/__tests__/consent/noUnmapped.test.ts
- packages/core/src/plugins/__tests__/consent/unmapped.test.ts
- packages/core/src/plugins/__tests__/consent/utils.ts
- packages/core/tsconfig.json
This work is direct derivative of @bsneed's https://github.com/segment-integrations/analytics-swift-consent/tree/main which in turn is a derivative of [consent test cases document](https://docs.google.com/document/d/1pcSWQShvyDOI-b2cx-NKc3iUqE_S40juSQK-KA6BMI8/edit).
This patch follows advisory of @bsneed and mirrors his work closely - so any amendments that follow will likely be applicable to both repositories.
> Consent plugin updates and test cases

- packages/core/src/__tests__/__helpers__/mockSegmentStore.ts
- packages/core/src/analytics.ts
- packages/core/src/plugins/ConsentPlugin.ts
- packages/core/src/plugins/__tests__/consent/destinationMultipleCategories.test.ts
- packages/core/src/plugins/__tests__/consent/mockSettings/ConsentNotEnabledAtSegment.json
- packages/core/src/plugins/__tests__/consent/mockSettings/DestinationsMultipleCategories.json
- packages/core/src/plugins/__tests__/consent/mockSettings/NoUnmappedDestinations.json
- packages/core/src/plugins/__tests__/consent/mockSettings/UnmappedDestinations.json
- packages/core/src/plugins/__tests__/consent/noUnmapped.test.ts
- packages/core/src/plugins/__tests__/consent/unmapped.test.ts
- packages/core/src/storage/sovranStorage.ts
- packages/core/src/storage/types.ts
- packages/core/src/types.ts
Implements the spec as explained [here](https://docs.google.com/document/d/13jxE3nwyn6pbUokOreJUFsfZtK7gjYq0JlPFLSUj21Y/edit)
Parity established with https://github.com/segment-integrations/analytics-swift-consent/commit/6563d95f6f1783bba4bd225d51fc849a48c7c3a5
> Add support for hasUnmappedDestinations

- packages/plugins/plugin-facebook-app-events/package.json
- packages/plugins/plugin-facebook-app-events/src/FacebookAppEventsPlugin.ts
- packages/plugins/plugin-facebook-app-events/src/__tests__/FacebookAppEventsPlugin.test.ts
- yarn.lock
- Adds `event_id` from `messageId` to the FB events to support deduplication
- Adds a `_logTime` unit test to verify the E notation error (no-repro)
- Bumps `FBSDK-Next` to latest
> fix(plugin-facebook): Fix Dedup issues in Facebook Plugin

- README.md
- examples/AnalyticsReactNativeExample/App.tsx
- examples/AnalyticsReactNativeExample/ios/Podfile.lock
- examples/AnalyticsReactNativeExample/package.json
- examples/AnalyticsReactNativeExample/yarn.lock
- packages/core/package.json
- packages/core/src/__tests__/api.test.ts
- packages/core/src/__tests__/context.test.ts
- packages/core/src/analytics.ts
- packages/core/src/client.tsx
- packages/core/src/context.ts
- packages/core/src/native-module.ts
- packages/core/src/plugins/__tests__/consent/idfa.test.ts
- packages/core/src/storage/__tests__/sovranStorage.test.ts
- packages/core/src/storage/sovranStorage.ts
- packages/core/src/storage/types.ts
- packages/core/src/test-helpers/setupSegmentClient.ts
- packages/core/src/types.ts
- packages/core/src/uuid.ts
- yarn.lock
Adds 2 new configuration options: `uuidProvider` and `deviceInfoProvider` to provide extensibility to other platforms like Windows, Web, Expo, etc.
```ts
export type UUIDProvider = () => string;
```
Supplies a simple UUID generator. By default it will try to use `react-native-get-random-values` unless one specific provider is passed. If the lib is not installed it will rely on JS random generators and log a warning
```ts
export type DeviceInfoProvider = (
config: GetContextConfig
) => Promise<NativeContextInfo>;
```
A function that returns the device context information. By default we will use our own native module if there's one available for the platform (Android & iOS).
> feat: add uuid and device info provider config

- packages/core/src/__tests__/analytics.test.ts
- packages/core/src/analytics.ts
- packages/core/src/flushPolicies/flush-policy-executer.ts
- packages/core/src/flushPolicies/startup-flush-policy.ts
- packages/core/src/plugins/QueueFlushingPlugin.ts
- packages/core/src/plugins/SegmentDestination.ts
- packages/core/src/util.ts
Problem reported that StartupFlushPolicy wouldn't send the pending upload events from the previous app launch. 
Caused by concurrency: FlushPolicies get initialized before and without awaiting for storage restoration. Futhermore the Queue for upload is managed by the SegmentDestination plugin so there's no explicit way to await for that queue to be restored from the base client itself.
Solution:
- Move the flush policy initialization later in the client: after plugins are initialized but before replaying buffered events
- Refactor StartupFlushPolicy to mark `shouldFlush` outside of `start` (this is to be able to handle it with the `manualFlush`)
- Refactor `QueueFlushingPlugin` and `SegmentDestination` to await for queue restoration and settings load when a flush is triggered. This …
> fix: startup flush policy should send restored events

- packages/plugins/plugin-idfa/ios/AnalyticsReactNativePluginIdfa.swift
- removes fallback to `idfv` value for `context.device.advertisingId` when a user asks app not to track
> fix: remove idfv fallback for idfa plugin

- packages/plugins/plugin-advertising-id/README.md
Addresses this issue: https://github.com/segmentio/analytics-react-native/issues/687
It seems like the issue was closed saying the AdMob setup is not necessary but the piece of documentation from the setup steps was not removed
> Removed the AdMob link from the setup instructions

- packages/plugins/plugin-facebook-app-events/src/FacebookAppEventsPlugin.ts
**Changes list**
- The `_valueToSum` attribute is mapped to properties however the `logEvent` method gets `valueToSum` [from the second argument](https://github.com/thebergamo/react-native-fbsdk-next/blob/bfd6d6e6c5a3d5e6e15b0e8acececd4cf0703ec0/src/FBAppEventsLogger.ts#L156)
**Demo instructions**
Using this plugin, send an event with the `price` or `value` field. You should see that value in the `_valueToSum` field in the corresponding Facebook event
> Fix: Pass `valueToSum` correctly to the Facebook SDK

- packages/plugins/plugin-appsflyer/src/AppsflyerPlugin.tsx
- packages/plugins/plugin-appsflyer/src/__tests__/AppsflyerPlugin.test.ts
Issue - Cannot configure `timeToWaitForATTUserAuthorization` for `AppsflyerPlugin`
Fix - Update the code for timeToWaitForATTUserAuthorization in AppsflyerPlugin to be configurable and if do not pass then it will pick the default added value of timeToWaitForATTUserAuthorization.
Tested the updated code on android emulator.
> Update timeToWaitForATTUserAuthorization in appsflyer plugin to be configurable

- packages/plugins/plugin-braze/package.json
- yarn.lock
Updated the braze react native sdk from 5.x to 10.x (latest version).
The latest version of braze react native sdk supports react native version 0.73 which is not supported in barze sdk 5.x.
Tested from local system using emulator.
> Upgrade braze react native sdk to 10.x

- README.md
Issue - The reset method is listed as having no parameters in the docs:
https://github.com/segmentio/analytics-react-native#reset
Fix - Updated the documentation with following information
When false is passed as an argument in reset method, it will skip resetting the anonymousId (but reset the rest of the user date)
> Reset() parameter documentation

- packages/plugins/plugin-firebase/src/methods/parameterMapping.ts
Issue : A customer wrote in with an issue about order_id not getting mapped to transaction_id as expected. From our external documentation it seems as though some mappings are missing with our React Native Firebase plugin.
Fix : Added the missing property mappings for the firebase plugin
> Added the missing property mappings for the firebase plugin

- packages/plugins/plugin-appsflyer/package.json
- fix version to get back inline with programmatic releases
> chore: bump appsflyer

- packages/core/package.json
- yarn.lock
- adds add strict dependency for `@stdlib/number-float64-base-normalizer` at `0.0.8`
- sets `@segment/tsub` dependency explicitly to `2.0.0`
- resolves #976
> fix: add `@stdlib/number-float64-base-normalize` dependency

- packages/core/src/timeline.ts
- packages/core/src/types.ts
* fix enrichment closure crash mentioned in #1011. the closure somehow gets injected as an object
* add enrichment closure to `userAnalytics` hook
> fix: check enrichment closure type before calling it

- packages/core/src/plugins/QueueFlushingPlugin.ts
An internal error occurred: [Error: Queue restoration timeout] #1008
> fix: to show 'Queue restoration timeout' only once

- packages/core/src/plugins/QueueFlushingPlugin.ts
- packages/plugins/plugin-advertising-id/src/AdvertisingIdPlugin.ts
Fix for - Advertising Id not being sent for Android Application Installed events using analytics-react-native-plugin-advertising-id #995
> fix: advertising id being sent for Android application installed events using analytics-react-native-plugin-advertsing-id

- packages/core/android/src/main/java/com/segmentanalyticsreactnative/AnalyticsReactNativeModule.kt
> Task :segment_analytics-react-native:compileDebugKotlin FAILED
e: file:///..../node_modules/@segment/analytics-react-native/android/src/main/java/com/segmentanalyticsreactnative/AnalyticsReactNativeModule.kt:128:30 Type mismatch: inferred type is String? but String was expected
> Fix: Type mismatch: inferred type is String? but String was expected

- packages/plugins/plugin-appsflyer/src/AppsflyerPlugin.tsx
Hi there!
Opening a PR here to solve an issue we've been having when trying to integrate with the Segment Appsflyer plugin.
We're running an Expo app using React Native 0.74.5 with Hermes.
When adding the plugin to our Segment instance (and going through the rest of the integration steps as described in the documentation), we'd see the attribution data on Appsflyer, together with all of our Segment tracking events, indicating the integration went well. What was missing, though, were the `Install Attributed` and `Organic Install` events on Segment. Interestingly, this was only the case on production builds, development clients were working just fine.
After diving into this issue, I figured out that the `onInstallConversionData` callback is called as expected with the right data, but the …
> fix: remove void promises from appsflyer plugin

- README.md
- examples/AnalyticsReactNativeExample/App.tsx
- examples/AnalyticsReactNativeExample/ios/AnalyticsReactNativeExample/PrivacyInfo.xcprivacy
- examples/AnalyticsReactNativeExample/ios/Podfile.lock
- examples/AnalyticsReactNativeExample/package.json
- examples/AnalyticsReactNativeExample/yarn.lock
- examples/E2E/App.tsx
- examples/E2E/e2e/mockServer.js
- packages/core/src/__tests__/internal/fetchSettings.test.ts
- packages/core/src/__tests__/util.test.ts
- packages/core/src/analytics.ts
- packages/core/src/constants.ts
- packages/core/src/plugins/SegmentDestination.ts
- packages/core/src/plugins/__tests__/SegmentDestination.test.ts
- packages/core/src/timeline.ts
- packages/core/src/types.ts
- packages/core/src/util.ts
- packages/plugins/plugin-appsflyer/src/AppsflyerPlugin.tsx
fix: for Unable to configure Custom Domain for React-Native
> fix: for Unable to configure Custom Domain for React-Native

- examples/E2E/App.tsx
- packages/core/src/__tests__/internal/fetchSettings.test.ts
- packages/core/src/__tests__/util.test.ts
- packages/core/src/analytics.ts
- packages/core/src/plugins/SegmentDestination.ts
- packages/core/src/plugins/__tests__/SegmentDestination.test.ts
- packages/core/src/util.ts
fix: The proxy URL is being altered in version 2.20.4, resulting in invalid URL
> fix: The proxy URL is being altered in version 2.20.4, resulting in invalid URL

- packages/core/src/analytics.ts
- packages/core/src/storage/sovranStorage.ts
- packages/core/src/storage/types.ts
- packages/core/src/test-helpers/mockSegmentStore.ts
- packages/core/src/test-helpers/setupSegmentClient.ts
feat: Ability to programmatically disable tracking
> feat: Ability to programmatically disable tracking

- packages/plugins/plugin-advertising-id/src/AdvertisingIdPlugin.ts
> enable event sending on iOS

- packages/plugins/plugin-appsflyer/src/AppsflyerPlugin.tsx
This PR is following up on #1025 - in that PR, I removed some usages of `void` Promises in the AppsFlyer plugin that weren't properly triggered in my project. I missed some of them in the same project, so following up here.
Let me know if you have any questions about this!
> fix: remove remaining void promises from appsflyer plugin

- packages/plugins/plugin-appsflyer/src/AppsflyerPlugin.tsx
This PR passes the three callbacks used in the appsflyer plugin out of the plugin as props.
[Appsflyer docs](https://dev.appsflyer.com/hc/docs/rn_unifieddeeplink) mention that the `onDeepLink` callback must be configured before initializing the SDK and as far as my testing goes, the callback cannot be defined more than once per SDK instance.
By adding props for the used callbacks, it's possible to use the callback logic used by the plugin and still specify custom deep link handlers.
Let me know if I'm missing something or if there is a better or easier way to solve this!
> feat: add callbacks to appsflyer plugin

- packages/sovran/README.md
In js/ts, if you want an arrow function to return an object in an inline manner, it needs to be surrounded by parenthesis.
> fix: example syntax is invalid
