segmentio/analytics-react-native

packages/integrations/template/index.d.ts.tpl

fix(integrations): fix TypeScript typings

---

packages/core/docs/interfaces/analytics.configuration.md

These descriptions were the wrong way round.

These descriptions were the wrong way round.

---

packages/integrations/template/android/build.gradle

Includes transitive destination dependencies. I did manually test this using Amplitude.
Fixes #34
Fixes #35
---
Ref: LIB-939

fix(android): fix missing classes at runtime

---

RELEASING.md

add documentation on how to use standard-version to prepare a release

docs(releasing): add releasing documentation

---

CHANGELOG.md
packages/core/package.json

* chore(release): 1.1.0-beta.1
* docs(changelog): fixed mixed up changelog entries

 chore(release): 1.1.0-beta.1 (#92)

---

packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt

PR #162 introduced a typo which fails debug builds, this PR fixes it.

fix(bridge): fix p(r)omise typo

---

packages/core/RNAnalytics.podspec
packages/core/android/build.gradle
packages/integrations/applyPatches.sh
packages/integrations/package.json
packages/integrations/patches/@segment/analytics-react-native-appsflyer/ios/main.m
packages/integrations/src/gen-integrations.ts
packages/integrations/src/integration-list.ts
packages/integrations/template/android/build.gradle
packages/integrations/template/ios/main.m

- Fixed issue with analytics-react-native reference in integration template.
- Fixed issue where includes couldn't be found on iOS when use_frameworks was enabled.

Miscellaneous fixes - WIP

---

packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt

I noticed that we werent parsing android specific options correctly. This PR will fix that.
fix is specific to sending data across the bridge, so no tests. I did verify by running on an emulator.

Fix(Android): Correctly parse android specific options

---

packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt

Add support for passing object integration data on Android.

feat(android): allow passing integration options

---

.circleci/config.yml
packages/core/RNAnalytics.podspec

- Unpinned analytics.
- Updated circleCI config to use latest Xcode.

chore(deps): unpinned analytics and updated CI to use latest xcode

---

packages/core/android/build.gradle

Switch android dependency to `4.+` so that it is always up-to-date

fix(android): bump android dependency

---

package.json
packages/test-app/patches/TestApp.xcodeproj/reactnative.xcworkspace/contents.xcworkspacedata
packages/test-app/patches/TestApp.xcodeproj/reactnative.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
packages/test-app/seed/package.json
yarn.lock

updated yarn and updated minimist to 0.2.1

chore: updated vulernable dependencies

---

packages/core/RNAnalytics.podspec

chore(dep): fix version requirement problems

---

packages/integrations/integrations.yml

fix(android): bump appsflyer version to something current

---

packages/integrations/template/android/src/main/java/com/segment/analytics/reactnative/integration/Module.kt

addresses issue: https://github.com/segmentio/analytics-react-native/issues/323

fix: change logging variable to constant string resolves error on 0.64.1

---

packages/integrations/integrations.yml

chore(deps): bump Segment-Firebase pod

---

package.json
packages/test-app/seed/package.json
yarn.lock

resolves security vulnerability in react native 0.64

chore(deps): bump react native

---

.release-it.js
package.json
yarn.lock

yarn `yarn release-it --dry-run` on a clean master (it will error out otherwise)  to see it publish all packages. Let me know if there's more customization we should do. This readme is really good 
https://github.com/rwjblue/release-it-yarn-workspaces

Release it

---

MIGRATION_GUIDE.md
packages/core/package.json
packages/core/src/__tests__/__helpers__/setup.js
packages/core/src/__tests__/store.test.ts
packages/core/src/store/index.ts
yarn.lock

The dependency https://www.npmjs.com/package/@react-native-community/async-storage is deprecated if favour of https://www.npmjs.com/package/@react-native-async-storage/async-storage

Point to @react-native-async-storage/async-storage dependency

---

packages/plugins/plugin-adjust/src/methods/__mocks__/react-native-adjust.ts
packages/plugins/plugin-adjust/src/methods/__tests__/track.test.ts
packages/plugins/plugin-adjust/src/methods/track.ts

The `trackEvent` call from Adjust was missing in the `track` method 🙈

[Adjust] Call trackEvent in the track method

---

packages/core/ios/AnalyticsReactNative.swift

Fixes https://github.com/segmentio/analytics-react-native/issues/398

[iOS] Fix `deviceType`

---

packages/plugins/plugin-adjust/src/AdjustPlugin.tsx

Fixes https://github.com/segmentio/analytics-react-native/issues/395

Remove update condition in plugin-adjust

---

packages/core/ios/AnalyticsReactNative.swift
packages/plugins/plugin-idfa/ios/AnalyticsReactNativePluginIdfa.swift

fix: add override fix to ios modules

---

example/ios/Podfile.lock
example/package.json
example/yarn.lock

resolves `node-fetch` dependency security vulnerability

fix: update react-native-gesture-handler

---

example/ios/Podfile.lock
example/src/App.tsx
packages/core/src/analytics.ts
packages/core/src/plugins/SegmentDestination.ts
packages/core/src/timeline.ts
packages/plugins/plugin-amplitudeSession/src/AmplitudeSessionPlugin.tsx

@oscb be sure to add a write-key to retrieve settings (i can dm you mine if needed) a test is currently failing too.

refactor: fix malformed context

---

.github/workflows/publish.yml

- ci: enable publish
- ci: fix publish on push

CI Enable publish

---

example/ios/Podfile.lock
example/package.json
example/yarn.lock

resolves security vulnerabilities

chore: bump react native dependency

---

example/ios/Podfile.lock
example/src/App.tsx
packages/plugins/plugin-adjust/src/AdjustPlugin.tsx

adds Adjust's `Attribution Callback` to track [`Install Attributed` ](https://github.com/adjust/react_native_sdk#attribution-callback)

feat: add install attribution callback to adjust plugin

---

example/e2e/mockServer.js
example/src/App.tsx
packages/core/src/__tests__/api.test.ts
packages/core/src/api.ts
packages/core/src/constants.ts

updates endpoint to account for metadata

Endpoint fix

---

packages/plugins/plugin-amplitudeSession/README.md

The import statement for the plugin is incorrect.

Fixed typo in README

---

packages/core/src/__tests__/methods/identify.test.ts
packages/core/src/events.ts
packages/core/src/types.ts
packages/plugins/plugin-braze/src/methods/identify.ts
packages/plugins/plugin-mixpanel/src/methods/__tests__/identify.test.ts
packages/plugins/plugin-mixpanel/src/methods/identify.ts
release.config.js

- chore: enable semantic-release
- fix: persist users traits across events

fix: persist user traits across events

---

packages/core/src/info.ts
packages/plugins/plugin-advertising-id/android/src/main/java/com/reactnativeanalyticsreactnativepluginadvertisingid/AnalyticsReactNativePluginAdvertisingIdModule.kt

Fix for NullPointerException as per here: https://github.com/segmentio/analytics-react-native/issues/643
And internal issue: LIBMOBILE-945

fix: do not attempt to cast null as ReactApplication

---

example/ios/Podfile.lock
example/package.json
packages/core/android/gradle.properties
packages/core/package.json
packages/core/src/info.ts

-Bump Koltin version to 1.6.0 to resolve build exception in Expo builds
-resolves #645 #646

fix: bump kotlin version

---

example/ios/AnalyticsReactNativeExample/AppDelegate.mm
example/ios/Podfile
example/ios/Podfile.lock
example/yarn.lock
packages/core/src/info.ts
packages/plugins/plugin-firebase/package.json
yarn.lock

- bumps `react-native-firebase` dependency to `15.4.0` in Firebase Plugin to use latest native modules

Bump firebase

---

packages/plugins/plugin-firebase/package.json

- bumps Firebase Destination Plugin to `0.3.2`

chore: prepare for release

---

example/ios/Podfile.lock
packages/core/src/info.ts
packages/plugins/plugin-advertising-id/android/gradle.properties

- Resolves build errors in new versions (0.69- 0.70) of React Native

fix: update kotlin version in adId plugin to resolve build errors

---

example/ios/Podfile.lock
packages/core/src/info.ts
packages/plugins/plugin-firebase/package.json

chore: publish firebase

---

MIGRATION_GUIDE.md
example/ios/Podfile.lock
example/yarn.lock
packages/core/package.json
packages/core/src/__mocks__/react-native.ts
packages/core/src/__tests__/uuid.test.ts
packages/core/src/uuid.ts
yarn.lock

fix: remove special anonymousID behaviour on dev mode

---

packages/core/src/index.ts

- adds `SegmentDestination` plugin to exports

fix: add SegmentDestination plugin to exports

---

packages/plugins/plugin-advertising-id/src/AdvertisingIdPlugin.ts

fix: check for platform before configuring adId plugin

---

README.md

Update README.md - add plugin

---

packages/plugins/plugin-firebase/package.json

- fixes build issue with example

fix: add firebase/app to dev dependencies

---

example/e2e/main.e2e.js
example/src/App.tsx
packages/core/src/plugins/QueueFlushingPlugin.ts
packages/sovran/src/persistor/async-storage-persistor.ts

- QueueFlushingPlugin now supports different store keys for different destination queues
- Reduce saveDelay to zero in queue to persist events immediately
- Warn if asyncStorage package is not present when using the AsyncStoragePersistor
- Added e2e tests for persistence

fix: queue storage fixes

---

packages/plugins/plugin-firebase/src/methods/parameterMapping.ts

- Adds mapping for Firebase `view_cart` event 
This fixes https://github.com/segmentio/analytics-react-native/issues/856

fix: add firebase view cart mapping

---

packages/plugins/plugin-idfa/README.md

Add some extra info about our IDFA docs.

Update IDFA docs

---

packages/core/src/analytics.ts

Reset anonymous id properly

---

packages/core/src/__tests__/analytics.test.ts

Issue - CI / build-and-test Failed
Fix - update the userInfo source in the analytics.test.ts

update userInfo source

---

packages/sovran/android/build.gradle

Issue :
Error when Launching Android Emulator: Could not find Kotlin Gradle Plugin
Fix : 
Added correct variable name to detect kotlin version.

Fix kotlin version issue

---

packages/core/src/__tests__/analytics.test.ts
packages/sovran/src/store.ts

issue :
CI / build-and-test Failed
Fix : 
Fix the changes for store info to run the test cases.

Fix test cases issue

---

packages/plugins/plugin-appsflyer/src/AppsflyerPlugin.tsx
packages/plugins/plugin-appsflyer/src/__tests__/AppsflyerPlugin.test.ts

Upgrade - Added ad_id, adset_id, adset attributes param to the Appsflyer plugin

Log more attribution params from Appsflyer

---

.github/workflows/ci.yml
packages/sovran/package.json
yarn.lock

- reverts anonymousId retrieval behavior in `reset()` method

fix: revert anonymousId get from store on reset

---

examples/E2E/e2e/main.e2e.js
packages/core/src/__tests__/context.test.ts
packages/core/src/context.ts

Fix library name to match 1.x library name.

fix:  update library name to match 1.x library name in context

---

examples/AnalyticsReactNativeExample/ios/Podfile.lock
examples/E2E/ios/Podfile.lock
packages/plugins/plugin-firebase/package.json
packages/sovran/package.json

- manually released `firebase-plugin` and `sovran` as they were out of sync with our CI 
- updates versions in `package.json` for respective packages

Chore: prepare for manual releases

---

packages/core/src/analytics.ts

TS2869: Right operand of ?? is unreachable because the left operand is never nullish.

---

packages/plugins/plugin-braze/package.json
yarn.lock

chore: upgraded Braze sdk version from 10.x to 14.x

chore: upgraded Braze sdk version from 10.x to 14.x

---

packages/core/package.json
packages/plugins/plugin-amplitudeSession/package.json

1. manually release core and amplitudeSessionID as semantic release is not working
2. updated versions in package.json for respective package

fix: preparing for manual release

---

packages/plugins/plugin-braze/package.json
packages/plugins/plugin-braze/src/BrazePlugin.tsx
yarn.lock

Updated Braze dependency from 14.x to 16.x
https://github.com/segmentio/analytics-react-native/issues/1091
https://github.com/segmentio/analytics-react-native/issues/1094

update: updated Braze plugin for Braze dependency

---

packages/core/android/src/main/java/com/segmentanalyticsreactnative/AnalyticsReactNativeModule.kt

fixes #1096
Note: haven't tested with old RN versions, might need a major version bump for this.

Fix build error on RN 0.81
